### ISSUE TITLE
Web Conversion to Waifu2x

### ISSUE THREAD

**Issue by hdublee** [imxieyi/waifu2x-ios-model-converter#11]
Something went wrong
'Unknown model. Please create an issue in https://github.com/imxieyi/waifu2x-ios-model-converter if it has a supported architecture.'

Model Link
https://github.com/Phhofm/models/raw/main/2xLexicaRRDBNet/2xLexicaRRDBNet_Sharp.pth

**Comment by imxieyi** [comment]
Done. Please try again using the web converter.
