### ISSUE TITLE
Web converter tool conversion help!

### ISSUE THREAD

**Issue by moondeaf** [imxieyi/waifu2x-ios-model-converter#12]
I'm trying to convert some .pth models I found on the old Model Database site and a few on the Open Model DB. It's been a lot of trial and error, and I'm making sure they're all the right supported architecture, but I'm still getting a lot of error messages for some of them. I'm not that familiar with converting models, or doing code of any sorts (I'm trying to learn and teach myself!)
Anyway, I'm trying to convert these models, and I'd appreciate it if they could be fixed _OR_ if someone could explain to me why some can't be converted:

- [eula_anifilm v1](https://openmodeldb.info/models/4x-eula-anifilm-v1)
- [eula digimanga MiA 65k](https://openmodeldb.info/models/4x-eula-digimanga-MiA-65k)
- [BooruGan 600k](https://drive.google.com/file/d/1DRyqqy24OU6G_mwsGjy6Zaxan_Fy1LNU/view?usp=sharing)
- [BooruGan 650k](https://drive.google.com/file/d/1psKp2DLWscPmDuzSTC8XqXL0LWnWuTYs/view?usp=sharing)
- [Futsuu Anime](https://openmodeldb.info/models/2x-Futsuu-Anime)
- [NMKD's Public ESRGAN Models; specifically all the Yandere models (it won't let me specifically link those folders/files)](https://icedrive.net/s/43GNBihZyi)

I apologize if this was a lot or if I'm not linking these correctly. The BooruGan files only takes me directly to the Drive page, but they were listed on the old upscale model database site/wiki. More than half of NMKD's models aren't working either, and it wouldn't let me directly link to each file, just the public page with all the folders. I half assumed that since some of eula's models were working, that they all would given the right architecture, but I'm having issues. Same goes for NMKD, since I recognize some of the existing models in the public folders.

Anyway, hopefully someone can help me, but if not it's cool. Thanks!

**Comment by imxieyi** [comment]
The automatic converter only works with [tested models](https://github.com/imxieyi/waifu2x-ios-model-converter/blob/master/known_models.yaml).

Support for the models you mentioned has been added to the converter. Some of them are also converted and added to the [drive folder](https://drive.google.com/drive/folders/1btfOExWcbO3qTN2uad61k2T0hBjCM0tv?usp=share_link).
