### ISSUE TITLE
Error code converting known models

### ISSUE THREAD

**Issue by moondeaf** [imxieyi/waifu2x-ios-model-converter#13]
Hello! I accidentally deleted some models I had imported into waifu2x, so I have to download, convert, and upload them again. I'm only converting the known models that are listed on the Hugging Face converter page. But I keep getting this error code on any I try to convert.

Here's a screenshot of the message I get:

![Screen Shot 2024-08-17 at 10 09 14 AM](https://github.com/user-attachments/assets/146bf10d-1c1c-4564-af15-c05cf120987d)

Is there anything I need to do, or is this an internal issue?

**Comment by moondeaf** [comment]
I should add that I forgot some were already converted and in the Google Drive, but this is still happening for the ones that aren't in that folder BUT are listed as a known model listed on the converter page.

**Comment by imxieyi** [comment]
The problem should be fixed now. Please try again.
