### ISSUE TITLE
Request to add support to convert a few more ESRGAN Models with the web model converter

### ISSUE THREAD

**Issue by pzlyk** [imxieyi/waifu2x-ios-model-converter#14]
Hello Yi Xie, would be possible for you to add support to convert the following models with the web model converter? When you have some time. Many thanks!

Nomos8kSC - https://openmodeldb.info/models/4x-Nomos8kSC
4x photo upscaler with otf jpg compression and blur, trained on musl's Nomos8k_sfw dataset for realisic sr.

4xNomos2_otf_esrgan - https://openmodeldb.info/models/4x-Nomos2-otf-esrgan
4x ESRGAN model for photography, trained using the Real-ESRGAN otf degradation pipeline.

4xNomosWebPhoto_esrgan - https://openmodeldb.info/models/4x-NomosWebPhoto-esrgan
4x ESRGAN model for photography, trained with realistic noise, lens blur, jpg and webp re-compression.

HFA2k - https://openmodeldb.info/models/4x-HFA2k
4x anime image upscaler with a bit of otf jpg compression and blur. Trained on musl's hfa2k dataset release for Anime SISR, which has been extracted from modern anime films, where the selection criteria was high SNR, no DOF and high frequency information.

4xLSDIR - https://openmodeldb.info/models/4x-LSDIR
A normal ESRGAN model without degradations and without any pretrain, simply an RRDBNet model trained on paired dataset (4x downsampled) on the full LSDIR dataset (84,991 images / 165 GB).

4xLSDIRplus - https://openmodeldb.info/models/4x-LSDIRplus
Interpolation of 4xLSDIRplusC and 4xLSDIRplusR to handle jpg compression and a little bit of noise/blur.

All of them are ESRGAN models with a CC-BY-4.0 license.

Thanks again!

**Comment by imxieyi** [comment]
Done. In fact CC-BY-4.0 is a permissive license. So converted models can be downloaded from [Google drive](https://drive.google.com/drive/folders/1btfOExWcbO3qTN2uad61k2T0hBjCM0tv?usp=share_link) as well.

**Comment by pzlyk** [comment]
> Done. In fact CC-BY-4.0 is a permissive license. So converted models can be downloaded from [Google drive](https://drive.google.com/drive/folders/1btfOExWcbO3qTN2uad61k2T0hBjCM0tv?usp=share_link) as well.

Thank you so much !!!
