### ISSUE TITLE
Model request: NKMD Superscale

### ISSUE THREAD

**Issue by fishnux** [imxieyi/waifu2x-ios-model-converter#16]
Model request: NKMD Superscale

I didn't have any luck trying to convert on my own. Thanks.

**Comment by imxieyi** [comment]
Done. All 4 variants are added. Feel free to download pre-converted models from [Google drive](https://drive.google.com/drive/folders/1btfOExWcbO3qTN2uad61k2T0hBjCM0tv?usp=share_link).
