### ISSUE TITLE
8x_NMKD-Typescale_175k.pth, 4x-TextSharpV1, 2x_BSTexty

### ISSUE THREAD

**Issue by sveinbjornpalsson** [imxieyi/waifu2x-ios-model-converter#5]
All three seem like they could be quite useful. For me they'd help with sharp vector graphics, for many others a special text upsampler opens up some csi type sh*t :D

**Comment by imxieyi** [comment]
`4x-TextSharpV1` is an alias of `4x-AnimeSharp` so you can just use `4x-AnimeSharp`.

`8x_NMKD-Typescale_175k` has been added to the drive folder as it has a permissive license.

`2x_BSTexty` is on GPLv3 so pre-converted model cannot be provided. Please go to [web converter](https://huggingface.co/spaces/imxieyi/waifu2x-ios-model-converter) and upload the original model file to get it converted.
