### ISSUE TITLE
Model Conversion Request

### ISSUE THREAD

**Issue by mslmn** [imxieyi/waifu2x-ios-model-converter#6]
I'd like to kindly request the conversion of the following models. 
`1x_eula_digimanga_bw_v3.pth`
`1x_MangaJPEGHQ.pth`
`1x_MangaJPEGHQPlus.pth`
`1x_MangaJPEGLQ.pth`
`1x_MangaJPEGMQ.pth`
`2x_MangaScaleV3.pth`
`4x_MangaJaNai_V0.5_100k.pth
`
Here's a mega [folder](https://mega.nz/folder/kvhlkZpI#vsbe5FGzxRIDiJoSgk8qGA) with all the .pth files.

Many thanks!

**Comment by imxieyi** [comment]
Where did `1x_eula_digimanga_bw_v3.pth` and `4x_MangaJaNai_V0.5_100k.pth` come from? They're not available on upscale.wiki.

**Comment by imxieyi** [comment]
Hmmm... Do you have a discord link to the digimanga model?

MangaJaNai doesn't have a license. I assume it's "All rights reserved".

**Comment by imxieyi** [comment]
Okay this discord server doesn't seem to be publicly accessible. It sounds like a bad idea adding a private model to supported models list.

I suggest that you install this converter locally. The following convert command works on my side:
```bash
python converter.py --type esrgan_old --name "1x eula digimanga bw v3" \
                    --scale 1 --monochrome --has-cuda --out-dir . \
                    1x_eula_digimanga_bw_v3.pth
```

MangaJPEG and MangaJaNai models have been added to both this repo and the web converter. Feel free to convert either online or this converter locally.

**Comment by imxieyi** [comment]
Done. Adding ESRGAN+ is quite simple. Somehow I skipped this one.
