### ISSUE TITLE
OmniSR Support

### ISSUE THREAD

**Issue by mslmn** [imxieyi/waifu2x-ios-model-converter#8]
Is it possible to add OmniSR support to the converter? I'd like to be able to convert this model

[4x_MangaJaNai_V1_RC16_OmniSR_100k.pth](https://mega.nz/file/9zASxbaJ#b3CQrg0gx02qpqC6GSUjW6DN1Y7kbwd6HzrOucwuE8c)

**Comment by imxieyi** [comment]
Unfortunately it's not currently possible to convert OmniSR to Core ML:
```
ValueError: Core ML only supports tensors with rank <= 5. Layer "x.9", with type "reshape", outputs a rank 6 tensor. 
```
